export enum EVENTTYPES {
  ERROR = 'error',
  UNHANDLEDREJECTION = 'unhandledrejection',
  CONSOLEERROR = 'consoleError',
  CLICK = 'click',
  LOAD = 'load',
  BEFOREUNLOAD = 'beforeunload',
  XHROPEN = 'xhrOpen',
  XHRSEND = 'xhrSend',
  FETCH = 'fetch',
  HASHCHANGE = 'hashchange',
  HISTORYPUSHSTATE = 'history-pushState',
  HISTORYREPLACESTATE = 'history-replaceState',
  POPSTATE = 'popstate',
  READYSTATECHANGE = 'readystatechange',
  ONLINE = 'online',
  OFFLINE = 'offline',
}
